// Sample Business Data - 50 Restaurants in Pune
const businesses = [
  {
    id: 1,
    name: "The Spice Garden",
    address: "123 FC Road, Shivaji Nagar, Pune 411005",
    phone: "+91 20 2567 8901",
    rating: 4.5,
    category: "Multi-Cuisine Restaurant",
    website: "https://spicegarden.com",
    hours: "11:00 AM - 11:00 PM",
    description:
      "A premium multi-cuisine restaurant offering a delightful blend of Indian, Chinese, and Continental flavors. Known for its elegant ambiance and exceptional service, The Spice Garden has been serving Pune's food lovers since 2010.",
  },
  {
    id: 2,
    name: "Maharaja's Kitchen",
    address: "45 JM Road, Deccan Gymkhana, Pune 411004",
    phone: "+91 20 2553 4567",
    rating: 4.8,
    category: "North Indian Restaurant",
    website: "https://maharajaskitchen.in",
    hours: "12:00 PM - 10:30 PM",
    description:
      "Experience royal dining with authentic North Indian cuisine. Our chefs bring the flavors of Punjab and Delhi right to your table with traditional recipes passed down through generations.",
  },
  {
    id: 3,
    name: "Coastal Flavors",
    address: "78 Baner Road, Baner, Pune 411045",
    phone: "+91 20 2729 1234",
    rating: 4.3,
    category: "Seafood Restaurant",
    website: "https://coastalflavors.com",
    hours: "12:00 PM - 11:00 PM",
    description:
      "Fresh seafood prepared with authentic coastal recipes. From Malvani fish curry to Goan prawn masala, we bring the best of India's coastline to Pune.",
  },
  {
    id: 4,
    name: "Green Leaf Cafe",
    address: "12 Koregaon Park, Pune 411001",
    phone: "+91 20 2612 5678",
    rating: 4.6,
    category: "Vegan & Organic Cafe",
    website: "https://greenleafcafe.in",
    hours: "8:00 AM - 9:00 PM",
    description:
      "A health-conscious cafe serving organic, vegan, and gluten-free options. Perfect for those who believe in eating clean while not compromising on taste.",
  },
  {
    id: 5,
    name: "Dragon Palace",
    address: "56 MG Road, Camp, Pune 411001",
    phone: "+91 20 2634 9012",
    rating: 4.4,
    category: "Chinese & Thai Restaurant",
    website: "https://dragonpalace.com",
    hours: "11:30 AM - 11:30 PM",
    description:
      "Authentic Asian cuisine featuring dishes from China, Thailand, and Vietnam. Our master chefs bring 20 years of experience to create unforgettable flavors.",
  },
  {
    id: 6,
    name: "Pizzeria Napoli",
    address: "89 Aundh Road, Aundh, Pune 411007",
    phone: "+91 20 2588 3456",
    rating: 4.7,
    category: "Italian Restaurant",
    website: "https://pizzerianapoli.in",
    hours: "11:00 AM - 11:00 PM",
    description:
      "Authentic Italian pizzas baked in a traditional wood-fired oven. Our dough is made fresh daily and imported ingredients ensure an authentic taste of Italy.",
  },
  {
    id: 7,
    name: "Tadka Express",
    address: "34 Sinhagad Road, Pune 411030",
    phone: "+91 20 2435 7890",
    rating: 4.2,
    category: "Street Food & Chaat",
    website: "https://tadkaexpress.com",
    hours: "10:00 AM - 10:00 PM",
    description:
      "The best of Indian street food under one roof. From Mumbai's pav bhaji to Delhi's golgappas, we serve all your street food favorites in a hygienic environment.",
  },
  {
    id: 8,
    name: "The Breakfast Club",
    address: "67 Viman Nagar, Pune 411014",
    phone: "+91 20 2668 2345",
    rating: 4.5,
    category: "Breakfast & Brunch",
    website: "https://thebreakfastclub.in",
    hours: "7:00 AM - 3:00 PM",
    description:
      "Start your day right with our extensive breakfast menu. From classic Indian breakfast to American pancakes, we have something for every morning craving.",
  },
  {
    id: 9,
    name: "Biryani House",
    address: "23 NIBM Road, Kondhwa, Pune 411048",
    phone: "+91 20 2683 6789",
    rating: 4.6,
    category: "Biryani Specialist",
    website: "https://biryanihouse.com",
    hours: "11:00 AM - 11:00 PM",
    description:
      "Authentic Hyderabadi and Lucknowi biryanis made with premium basmati rice and secret spice blends. Our dum cooking technique ensures every grain is perfectly flavored.",
  },
  {
    id: 10,
    name: "Sushi Samurai",
    address: "45 Kalyani Nagar, Pune 411006",
    phone: "+91 20 2665 1234",
    rating: 4.8,
    category: "Japanese Restaurant",
    website: "https://sushisamurai.in",
    hours: "12:00 PM - 10:30 PM",
    description:
      "Premium Japanese dining experience with fresh sushi, sashimi, and traditional dishes. Our chefs are trained in Tokyo and bring authentic Japanese flavors to Pune.",
  },
  {
    id: 11,
    name: "The Grill Room",
    address: "78 Senapati Bapat Road, Pune 411016",
    phone: "+91 20 2567 4567",
    rating: 4.4,
    category: "Steakhouse & Grill",
    website: "https://thegrillroom.com",
    hours: "6:00 PM - 11:30 PM",
    description:
      "Premium steaks and grilled meats cooked to perfection. We source the finest cuts and age them in-house for maximum flavor and tenderness.",
  },
  {
    id: 12,
    name: "Cafe Mocha",
    address: "12 Oxford Street, Camp, Pune 411001",
    phone: "+91 20 2634 8901",
    rating: 4.3,
    category: "Coffee House & Bakery",
    website: "https://cafemocha.in",
    hours: "8:00 AM - 11:00 PM",
    description:
      "Artisanal coffee and freshly baked goods in a cozy atmosphere. We roast our own beans and our pastry chefs create delightful treats daily.",
  },
  {
    id: 13,
    name: "Rasoi Kitchen",
    address: "56 Karve Road, Kothrud, Pune 411038",
    phone: "+91 20 2546 2345",
    rating: 4.5,
    category: "Gujarati & Rajasthani",
    website: "https://rasoikitchen.com",
    hours: "11:00 AM - 3:30 PM, 7:00 PM - 10:30 PM",
    description:
      "Authentic Gujarati and Rajasthani thalis served with love. Experience the true taste of Western India with our unlimited thali offerings.",
  },
  {
    id: 14,
    name: "La Patisserie",
    address: "89 Boat Club Road, Pune 411001",
    phone: "+91 20 2612 6789",
    rating: 4.7,
    category: "French Bakery & Cafe",
    website: "https://lapatisserie.in",
    hours: "9:00 AM - 9:00 PM",
    description:
      "Exquisite French pastries and desserts crafted by our Paris-trained pastry chef. From croissants to macarons, taste France in every bite.",
  },
  {
    id: 15,
    name: "Wok & Roll",
    address: "34 Wakad Road, Wakad, Pune 411057",
    phone: "+91 20 2729 3456",
    rating: 4.2,
    category: "Pan-Asian Restaurant",
    website: "https://wokandroll.com",
    hours: "11:30 AM - 11:00 PM",
    description:
      "A culinary journey through Asia with dishes from China, Thailand, Japan, and Korea. Our open kitchen lets you watch the magic happen.",
  },
  {
    id: 16,
    name: "Dosa Corner",
    address: "67 Tilak Road, Sadashiv Peth, Pune 411030",
    phone: "+91 20 2447 7890",
    rating: 4.4,
    category: "South Indian Restaurant",
    website: "https://dosacorner.in",
    hours: "7:00 AM - 10:00 PM",
    description:
      "Crispy dosas, fluffy idlis, and flavorful sambar - we serve authentic South Indian breakfast and meals that transport you to Chennai.",
  },
  {
    id: 17,
    name: "The BBQ Nation",
    address: "23 Phoenix Mall, Viman Nagar, Pune 411014",
    phone: "+91 20 2668 1234",
    rating: 4.6,
    category: "Barbecue Restaurant",
    website: "https://thebbqnation.com",
    hours: "12:00 PM - 3:30 PM, 6:30 PM - 11:00 PM",
    description:
      "Live grill experience with unlimited starters and main course. Watch your food sizzle on the table-top grill while enjoying our extensive buffet.",
  },
  {
    id: 18,
    name: "Kebab Factory",
    address: "45 Residency Road, Camp, Pune 411001",
    phone: "+91 20 2634 5678",
    rating: 4.5,
    category: "Mughlai Restaurant",
    website: "https://kebabfactory.in",
    hours: "12:00 PM - 11:00 PM",
    description:
      "Succulent kebabs and rich Mughlai curries prepared in traditional tandoor. Our secret marinades have been perfected over decades.",
  },
  {
    id: 19,
    name: "Pasta Paradise",
    address: "78 Lane 5, Koregaon Park, Pune 411001",
    phone: "+91 20 2612 9012",
    rating: 4.3,
    category: "Italian Bistro",
    website: "https://pastaparadise.com",
    hours: "11:00 AM - 11:00 PM",
    description:
      "Handmade pasta and authentic Italian sauces. We make our pasta fresh daily using traditional techniques and premium ingredients.",
  },
  {
    id: 20,
    name: "Curry Leaves",
    address: "12 Magarpatta City, Hadapsar, Pune 411028",
    phone: "+91 20 2689 3456",
    rating: 4.4,
    category: "Kerala Restaurant",
    website: "https://curryleaves.in",
    hours: "11:30 AM - 10:30 PM",
    description:
      "Authentic Kerala cuisine featuring traditional recipes. From appam with stew to fish molee, experience God's Own Country on your plate.",
  },
  {
    id: 21,
    name: "The Burger Joint",
    address: "56 Model Colony, Shivaji Nagar, Pune 411016",
    phone: "+91 20 2567 7890",
    rating: 4.5,
    category: "American Diner",
    website: "https://theburgerjoint.com",
    hours: "11:00 AM - 11:00 PM",
    description:
      "Gourmet burgers with premium patties and artisanal buns. We grind our meat fresh and use only the best ingredients for our classic American burgers.",
  },
  {
    id: 22,
    name: "Taj Mahal Palace",
    address: "89 University Road, Ganeshkhind, Pune 411007",
    phone: "+91 20 2567 1234",
    rating: 4.7,
    category: "Fine Dining Indian",
    website: "https://tajmahalpalace.in",
    hours: "12:00 PM - 3:00 PM, 7:00 PM - 11:00 PM",
    description:
      "Experience luxury dining with royal Indian cuisine. Our award-winning chefs create masterpieces that honor India's rich culinary heritage.",
  },
  {
    id: 23,
    name: "Noodle Bar",
    address: "34 Lane 7, Koregaon Park, Pune 411001",
    phone: "+91 20 2612 5678",
    rating: 4.2,
    category: "Asian Noodles & Soups",
    website: "https://noodlebar.com",
    hours: "11:00 AM - 10:30 PM",
    description:
      "Handmade noodles and soul-warming soups from across Asia. Watch our chefs pull and stretch fresh noodles for your bowl.",
  },
  {
    id: 24,
    name: "The Chocolate Room",
    address: "67 FC Road, Shivaji Nagar, Pune 411005",
    phone: "+91 20 2553 9012",
    rating: 4.6,
    category: "Dessert Cafe",
    website: "https://thechocolateroom.in",
    hours: "10:00 AM - 11:00 PM",
    description:
      "A chocolate lover's paradise with decadent desserts and beverages. Everything from fondues to shakes, we celebrate chocolate in every form.",
  },
  {
    id: 25,
    name: "Punjab Grill",
    address: "23 Bund Garden Road, Pune 411001",
    phone: "+91 20 2612 3456",
    rating: 4.5,
    category: "Punjabi Restaurant",
    website: "https://punjabgrill.com",
    hours: "12:00 PM - 11:00 PM",
    description:
      "Hearty Punjabi food with generous portions and bold flavors. Our butter chicken and dal makhani are legendary in Pune.",
  },
  {
    id: 26,
    name: "Mediterranean Bistro",
    address: "45 Boat Club Road, Pune 411001",
    phone: "+91 20 2612 7890",
    rating: 4.4,
    category: "Mediterranean Cuisine",
    website: "https://mediterraneanbistro.in",
    hours: "11:30 AM - 10:30 PM",
    description:
      "Fresh Mediterranean flavors with Greek, Turkish, and Lebanese influences. Our hummus and falafel are made from scratch daily.",
  },
  {
    id: 27,
    name: "Rice Bowl",
    address: "78 Hinjewadi Road, Hinjewadi, Pune 411057",
    phone: "+91 20 2293 1234",
    rating: 4.3,
    category: "Chinese Fast Casual",
    website: "https://ricebowl.com",
    hours: "11:00 AM - 10:00 PM",
    description:
      "Quick and delicious Chinese rice bowls and combos. Perfect for a satisfying meal during your busy workday in the IT hub.",
  },
  {
    id: 28,
    name: "Satvik Bhojanala",
    address: "12 Narayan Peth, Pune 411030",
    phone: "+91 20 2447 5678",
    rating: 4.7,
    category: "Pure Vegetarian Thali",
    website: "https://satvikbhojanala.in",
    hours: "11:00 AM - 3:00 PM, 7:00 PM - 10:00 PM",
    description:
      "Traditional Maharashtrian and South Indian vegetarian meals. Our thalis are prepared with love using age-old family recipes.",
  },
  {
    id: 29,
    name: "Taco Town",
    address: "56 Pimple Saudagar, Pune 411027",
    phone: "+91 20 2729 9012",
    rating: 4.2,
    category: "Mexican Restaurant",
    website: "https://tacotown.com",
    hours: "11:00 AM - 11:00 PM",
    description:
      "Authentic Mexican tacos, burritos, and quesadillas. Our salsas are made fresh and our tortillas are pressed to order.",
  },
  {
    id: 30,
    name: "The Tea Lounge",
    address: "89 Camp, Pune 411001",
    phone: "+91 20 2634 3456",
    rating: 4.5,
    category: "Tea House & Light Bites",
    website: "https://thetealounge.in",
    hours: "10:00 AM - 9:00 PM",
    description:
      "A curated collection of teas from around the world paired with light snacks. The perfect spot for a peaceful afternoon break.",
  },
  {
    id: 31,
    name: "Patang Revolving Restaurant",
    address: "34 Baner Hill, Baner, Pune 411045",
    phone: "+91 20 2729 7890",
    rating: 4.8,
    category: "Multi-Cuisine Fine Dining",
    website: "https://patangrestaurant.com",
    hours: "12:00 PM - 3:00 PM, 7:00 PM - 11:00 PM",
    description:
      "Pune's iconic revolving restaurant offering panoramic city views. Enjoy fine dining while the city unfolds around you.",
  },
  {
    id: 32,
    name: "Chulha Chauka",
    address: "67 Paud Road, Kothrud, Pune 411038",
    phone: "+91 20 2546 1234",
    rating: 4.4,
    category: "Maharashtrian Restaurant",
    website: "https://chulhachauka.in",
    hours: "11:00 AM - 10:30 PM",
    description:
      "Authentic Maharashtrian food cooked on traditional chulha. Experience the rustic flavors of rural Maharashtra in every bite.",
  },
  {
    id: 33,
    name: "Fusion Hub",
    address: "23 Kalyani Nagar, Pune 411006",
    phone: "+91 20 2665 5678",
    rating: 4.3,
    category: "Fusion Cuisine",
    website: "https://fusionhub.com",
    hours: "12:00 PM - 11:00 PM",
    description:
      "Creative fusion dishes that blend cuisines from around the world. Our innovative chefs create unique flavor combinations you won't find anywhere else.",
  },
  {
    id: 34,
    name: "The Ice Cream Story",
    address: "45 FC Road, Shivaji Nagar, Pune 411005",
    phone: "+91 20 2553 9012",
    rating: 4.6,
    category: "Artisanal Ice Cream",
    website: "https://theicecreamstory.in",
    hours: "11:00 AM - 11:00 PM",
    description:
      "Handcrafted ice creams in unique local flavors. From mango chili to rose cardamom, our flavors tell stories of India.",
  },
  {
    id: 35,
    name: "Dhaba 101",
    address: "78 Mumbai-Pune Highway, Pune 411046",
    phone: "+91 20 2729 3456",
    rating: 4.2,
    category: "Highway Dhaba Style",
    website: "https://dhaba101.com",
    hours: "24 Hours",
    description:
      "Authentic highway dhaba experience with robust Punjabi and North Indian food. Open 24/7 for those late-night cravings.",
  },
  {
    id: 36,
    name: "Sakura Japanese Kitchen",
    address: "12 Koregaon Park Annexe, Pune 411001",
    phone: "+91 20 2612 7890",
    rating: 4.5,
    category: "Japanese Izakaya",
    website: "https://sakurakitchen.in",
    hours: "6:00 PM - 11:30 PM",
    description:
      "Traditional Japanese izakaya serving small plates, sake, and authentic Japanese spirits. A slice of Tokyo nightlife in Pune.",
  },
  {
    id: 37,
    name: "Bombay Blue",
    address: "56 Bund Garden Road, Pune 411001",
    phone: "+91 20 2612 1234",
    rating: 4.4,
    category: "Indian Casual Dining",
    website: "https://bombayblue.com",
    hours: "11:00 AM - 11:00 PM",
    description:
      "Casual Indian dining with a focus on Mumbai street food and coastal cuisine. Comfort food done right.",
  },
  {
    id: 38,
    name: "The Greek House",
    address: "89 Lane 6, Koregaon Park, Pune 411001",
    phone: "+91 20 2612 5678",
    rating: 4.6,
    category: "Greek Restaurant",
    website: "https://thegreekhouse.in",
    hours: "12:00 PM - 10:30 PM",
    description:
      "Authentic Greek cuisine with traditional recipes from the Mediterranean. Our souvlaki and moussaka transport you to Santorini.",
  },
  {
    id: 39,
    name: "Terrace by O Hotel",
    address: "34 North Main Road, Koregaon Park, Pune 411001",
    phone: "+91 20 2612 9012",
    rating: 4.7,
    category: "Rooftop Restaurant & Bar",
    website: "https://terracebyohotel.com",
    hours: "5:00 PM - 1:00 AM",
    description:
      "Stunning rooftop dining with city views. Perfect for sundowners and romantic dinners under the stars.",
  },
  {
    id: 40,
    name: "Konkan Kitchen",
    address: "67 Prabhat Road, Deccan, Pune 411004",
    phone: "+91 20 2553 3456",
    rating: 4.5,
    category: "Konkan Coastal Cuisine",
    website: "https://konkankitchen.in",
    hours: "11:30 AM - 10:30 PM",
    description:
      "Authentic Malvani and Konkani cuisine from India's western coast. Fresh fish curry and sol kadhi that taste like home.",
  },
  {
    id: 41,
    name: "Bagel Bros",
    address: "23 Baner Road, Baner, Pune 411045",
    phone: "+91 20 2729 7890",
    rating: 4.3,
    category: "Bagel Cafe",
    website: "https://bagelbros.com",
    hours: "8:00 AM - 8:00 PM",
    description:
      "New York style bagels made fresh daily. From classic cream cheese to loaded bagel sandwiches, we do bagels right.",
  },
  {
    id: 42,
    name: "Spice Route",
    address: "45 Magarpatta City, Hadapsar, Pune 411028",
    phone: "+91 20 2689 1234",
    rating: 4.4,
    category: "Pan-Indian Restaurant",
    website: "https://spiceroute.in",
    hours: "12:00 PM - 11:00 PM",
    description:
      "A culinary journey through India featuring regional specialties from every corner of the country. One menu, many Indias.",
  },
  {
    id: 43,
    name: "The Wine Company",
    address: "78 Senapati Bapat Road, Pune 411016",
    phone: "+91 20 2567 5678",
    rating: 4.6,
    category: "Wine Bar & Bistro",
    website: "https://thewinecompany.com",
    hours: "4:00 PM - 12:00 AM",
    description:
      "Extensive wine selection paired with European cuisine. Our sommelier helps you find the perfect pairing for every dish.",
  },
  {
    id: 44,
    name: "Chai Point",
    address: "12 Hinjewadi IT Park, Pune 411057",
    phone: "+91 20 2293 9012",
    rating: 4.2,
    category: "Chai Cafe",
    website: "https://chaipoint.com",
    hours: "7:00 AM - 10:00 PM",
    description:
      "India's favorite beverage served in countless varieties. From masala chai to kulhad chai, we celebrate tea culture.",
  },
  {
    id: 45,
    name: "Korean Haus",
    address: "56 Kalyani Nagar, Pune 411006",
    phone: "+91 20 2665 3456",
    rating: 4.5,
    category: "Korean Restaurant",
    website: "https://koreanhaus.in",
    hours: "12:00 PM - 10:30 PM",
    description:
      "Authentic Korean cuisine with tabletop BBQ. Our kimchi is made in-house and our K-pop playlist sets the mood.",
  },
  {
    id: 46,
    name: "The Mill",
    address: "89 Mundhwa Road, Pune 411036",
    phone: "+91 20 2695 7890",
    rating: 4.4,
    category: "Microbrewery & Kitchen",
    website: "https://themill.com",
    hours: "12:00 PM - 1:00 AM",
    description:
      "Craft beers brewed on-site paired with elevated bar food. Watch our brewmasters at work while you enjoy fresh brews.",
  },
  {
    id: 47,
    name: "Anatolia",
    address: "34 Koregaon Park, Pune 411001",
    phone: "+91 20 2612 1234",
    rating: 4.6,
    category: "Turkish Restaurant",
    website: "https://anatolia.in",
    hours: "12:00 PM - 11:00 PM",
    description:
      "Ottoman cuisine featuring traditional Turkish dishes. From doner kebabs to baklava, experience the flavors of Istanbul.",
  },
  {
    id: 48,
    name: "The Pancake House",
    address: "67 Viman Nagar, Pune 411014",
    phone: "+91 20 2668 5678",
    rating: 4.3,
    category: "Pancake & Waffle Cafe",
    website: "https://thepancakehouse.com",
    hours: "8:00 AM - 10:00 PM",
    description:
      "Fluffy pancakes and crispy waffles in endless varieties. Sweet or savory, we have pancakes for every mood.",
  },
  {
    id: 49,
    name: "Masala Bay",
    address: "23 Boat Club Road, Pune 411001",
    phone: "+91 20 2612 9012",
    rating: 4.7,
    category: "Coastal Fine Dining",
    website: "https://masalabay.in",
    hours: "12:00 PM - 3:00 PM, 7:00 PM - 11:00 PM",
    description:
      "Premium coastal Indian cuisine featuring the best of Kerala, Goa, and Mangalore. Fresh seafood in elegant preparations.",
  },
  {
    id: 50,
    name: "The Farm House",
    address: "45 Lavale Road, Mulshi, Pune 411057",
    phone: "+91 20 2293 3456",
    rating: 4.8,
    category: "Farm-to-Table Restaurant",
    website: "https://thefarmhouse.com",
    hours: "11:00 AM - 10:00 PM",
    description:
      "Fresh, organic ingredients sourced from our own farm. Enjoy a rustic dining experience surrounded by nature just outside the city.",
  },
];

// Export for use in other scripts
if (typeof module !== "undefined" && module.exports) {
  module.exports = { businesses };
}
